version: '3'
services:
  cra:
    environment:
      OUTPUT_DIRECTORY: ${OUTPUT_DIRECTORY}
      CONTAINER_PORT: ${CONTAINER_PORT}
      HOST_PORT: ${HOST_PORT}
    build:
      context: './'
      dockerfile: Dockerfile
    container_name: 'createReactAppExecutor'
    working_dir: '/app'

